version: '3.8'

services:
  # MySQL 数据库服务, version : 8.0
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/mysql/init:/docker-entrypoint-initdb.d  # 挂载初始化脚本
    networks:
      - app-network
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5


  # FastAPI 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    volumes:
      - ./backend:/backend:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    container_name: backend
    environment:
      DATABASE_URL: mysql+aiomysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      FASTAPI_ENV: ${FASTAPI_ENV}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

# 网络和卷配置
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: